mp_id: mp-3953

globals:
  duration: 10.0   
  temp: 300

jobs:
  - name: one
    mode: spectral
    sites: all

  - name: two
    mode: choral
    sites: Ca_1

  - name: three
    mode: synth
    sites: [O_1,Ca_1]

mix:
  output: CaO_mix.wav
  fade: 4.0          
  curve: tri        
  mode: concat  
  order: random 18 

