globals:
  duration: 10.0   
  mp_id: mp-66
  fmin_phonon: 1e10
  fmax_phonon: 4e13
  overwrite: True

jobs:
  - name: one
    mode: synth
    sites: C_1

  - name: two
    mode: choral
    sites: C_1

mix:
  output: diamond_test_mix.wav
  fade: 9.0          
  curve: tri        
  mode: super  
  # order: ["one", "six", "two","three","six", "five", "three", "five"]
  weight:
    one: 0.3
    two: 0.7

